server:
  port: 8888
  servlet:
    context-path: /euphonyqr

QIESHU:
  APPKEY: "8c27d7*******d48df7" #箧书声波解析token公钥
  SECKEY: "48fa3f*******113853"  #箧书声波解析token秘钥
  WXAPPID: "wx8d1*******af8c5"   #对应上面应用注册时wxId
  PACKAGE_NAME: ""
  BOUND_ID: ""
  SANDBOX: false   #用户调试开关， false  用于正式环境
  CHECKWXAPPID: false